configuration:
  width: 450
  height: 450
  luminosity-label: '%1$.0f fb^{-1} at #sqrt{s} = 13 TeV'
  experiment: " Delphes Sim"
  #extra-label: "Preliminary"
  extra-label: "Signal * 10^{4}"
  root: ''
  luminosity: 3000000
  yields-table-align: v
  book-keeping-file: 'plots.root'

files: 
  include: ['files.yml']

plots:
  include: ['histos.yml']

legend:
  position: [0.18, 0.79, 0.95, 0.91]
  columns: 5

groups:
  include: ['groups.yml']

