'hist_LQcmutauLO.root':
  type: signal
  pretty-name: 'LQcmutauLO'
  cross-section: 0.00083176
  generated-events: 100000
  line-color: '#00ffff'
  legend: '#mu#tau'
  scale: 10000
  order: 1

'hist_LQcnunuLO.root':
  type: signal
  pretty-name: 'LQcnunuLO'
  cross-section: 0.00083176
  generated-events: 100000
  line-color: '#ffff00'
  legend: '#nu#nu'
  scale: 10000
  order: 2

'hist_LQctautauLO.root':
  type: signal
  pretty-name: 'LQctautauLO'
  cross-section: 0.00083176
  generated-events: 100000
  line-color: '#ff0000'
  legend: '#tau#tau'
  scale: 10000
  order: 3

'hist_DY012JetsM10toinf.root':
  type: mc
  pretty-name: 'DY012JetsM10toinf'
  cross-section: 24375.4
  generated-events: 1352998
  fill-color: "#000099"
  legend: "DY"
  order: 0

'hist_W0JetsToLNu.root':
  type: mc
  pretty-name: 'W0JetsToLNu'
  cross-section: 47071
  generated-events: 750000
  fill-color: '#ff9933'
  group: GWJets
  order: 1

'hist_W1JetsToLNu.root':
  type: mc
  pretty-name: 'W1JetsToLNu'
  cross-section: 9816
  generated-events: 376230
  fill-color: '#ff9933'
  group: GWJets
  order: 2

'hist_W2JetsToLNu.root':
  type: mc
  pretty-name: 'W2JetsToLNu'
  cross-section: 3200
  generated-events: 196803
  fill-color: '#ff9933'
  group: GWJets
  order: 3

'hist_TT012Jets.root':
  type: mc
  pretty-name: 'TT012Jets'
  cross-section: 831.76
  generated-events: 983666
  fill-color: '#ff6666'
  legend: 'TT'
  order: 4

'hist_WW.root':
  type: mc
  pretty-name: 'WW'
  cross-section: 118.7
  generated-events: 500000
  fill-color: '#cc00cc'
  legend: 'WW'
  order: 5

'hist_WZ.root':
  type: mc
  pretty-name: 'WZ'
  cross-section: 47.13
  generated-events: 500000
  fill-color: '#9933ff'
  legend: 'WZ'
  order: 6

'hist_ZZ.root':
  type: mc
  pretty-name: 'ZZ'
  cross-section: 16.523
  generated-events: 500000
  fill-color: '#660066'
  legend: 'ZZ'
  order: 7
